### ISSUE TITLE
Data set download error

### ISSUE THREAD

**Issue by LinyeLi60** [MengyuanChen21/ICLR2024-REDL#2]
> ----------
> Untarring features.tar:
> tar: 它似乎不像是一个 tar 归档文件
> tar: 跳转到下一个头
> tar: 由于前次错误，将以上次的错误状态退出
> ----------
> md5sum: features.md5: 没有那个文件或目录

==> After extracting the md5sum checks did not match. 
    Either the downloaded file was corrupted 
    or the untarring went wrong or sth fishy happend.
    (most probably, of the first two).
Hello, I use `bash ./features/download.sh` to download the dataset, but I got this error.

**Comment by MengyuanChen21** [comment]
You are right. Thanks for pointing out the issue. I have just run the script and encountered the same error. Since I did not provide the download link, I am unsure how to fix it, but I can share my downloaded file with you.

You can download the zip file from [Google Drive](https://drive.google.com/file/d/1yJC4xABAPkidHYEddZ6ncUgKaRIxNy6L/view?usp=drive_link) and place its contents ("features.md5" and "WideResNet28_10_S2M2_R") directly into the "code_fsl/features/" directory.
